declare const config: import("@tamagui/web").TamaguiInternalConfig<{
    color: {
        primary: import("@tamagui/web").Variable<string>;
        primaryHover: import("@tamagui/web").Variable<string>;
        primaryPress: import("@tamagui/web").Variable<string>;
        primaryFocus: import("@tamagui/web").Variable<string>;
        success: import("@tamagui/web").Variable<string>;
        successHover: import("@tamagui/web").Variable<string>;
        successPress: import("@tamagui/web").Variable<string>;
        warning: import("@tamagui/web").Variable<string>;
        warningHover: import("@tamagui/web").Variable<string>;
        warningPress: import("@tamagui/web").Variable<string>;
        error: import("@tamagui/web").Variable<string>;
        errorHover: import("@tamagui/web").Variable<string>;
        errorPress: import("@tamagui/web").Variable<string>;
        white: import("@tamagui/web").Variable<string>;
        black: import("@tamagui/web").Variable<string>;
        transparent: import("@tamagui/web").Variable<string>;
        neutral0: import("@tamagui/web").Variable<string>;
        neutral1: import("@tamagui/web").Variable<string>;
        neutral2: import("@tamagui/web").Variable<string>;
        neutral3: import("@tamagui/web").Variable<string>;
        neutral4: import("@tamagui/web").Variable<string>;
        neutral5: import("@tamagui/web").Variable<string>;
        neutral6: import("@tamagui/web").Variable<string>;
        neutral7: import("@tamagui/web").Variable<string>;
        neutral8: import("@tamagui/web").Variable<string>;
        neutral9: import("@tamagui/web").Variable<string>;
        neutral10: import("@tamagui/web").Variable<string>;
        neutral11: import("@tamagui/web").Variable<string>;
        neutral12: import("@tamagui/web").Variable<string>;
    };
    space: {
        0: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
        24: import("@tamagui/web").Variable<number>;
    };
    size: {
        0: import("@tamagui/web").Variable<number>;
        true: import("@tamagui/web").Variable<number>;
        0.5: import("@tamagui/web").Variable<number>;
        1.5: import("@tamagui/web").Variable<number>;
        2.5: import("@tamagui/web").Variable<number>;
        3.5: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
        24: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
    };
    radius: {
        0: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        full: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
    };
    zIndex: {
        0: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        modal: import("@tamagui/web").Variable<number>;
        toast: import("@tamagui/web").Variable<number>;
        tooltip: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
    };
} & Omit<{
    size: {
        0: import("@tamagui/web").Variable<number>;
        true: import("@tamagui/web").Variable<number>;
        0.5: import("@tamagui/web").Variable<number>;
        1.5: import("@tamagui/web").Variable<number>;
        2.5: import("@tamagui/web").Variable<number>;
        3.5: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
        24: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
    };
    space: {
        0: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
        24: import("@tamagui/web").Variable<number>;
    };
    radius: {
        0: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        full: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
    };
    zIndex: {
        0: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        modal: import("@tamagui/web").Variable<number>;
        toast: import("@tamagui/web").Variable<number>;
        tooltip: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
    };
    color: {
        primary: import("@tamagui/web").Variable<string>;
        primaryHover: import("@tamagui/web").Variable<string>;
        primaryPress: import("@tamagui/web").Variable<string>;
        primaryFocus: import("@tamagui/web").Variable<string>;
        success: import("@tamagui/web").Variable<string>;
        successHover: import("@tamagui/web").Variable<string>;
        successPress: import("@tamagui/web").Variable<string>;
        warning: import("@tamagui/web").Variable<string>;
        warningHover: import("@tamagui/web").Variable<string>;
        warningPress: import("@tamagui/web").Variable<string>;
        error: import("@tamagui/web").Variable<string>;
        errorHover: import("@tamagui/web").Variable<string>;
        errorPress: import("@tamagui/web").Variable<string>;
        white: import("@tamagui/web").Variable<string>;
        black: import("@tamagui/web").Variable<string>;
        transparent: import("@tamagui/web").Variable<string>;
        neutral0: import("@tamagui/web").Variable<string>;
        neutral1: import("@tamagui/web").Variable<string>;
        neutral2: import("@tamagui/web").Variable<string>;
        neutral3: import("@tamagui/web").Variable<string>;
        neutral4: import("@tamagui/web").Variable<string>;
        neutral5: import("@tamagui/web").Variable<string>;
        neutral6: import("@tamagui/web").Variable<string>;
        neutral7: import("@tamagui/web").Variable<string>;
        neutral8: import("@tamagui/web").Variable<string>;
        neutral9: import("@tamagui/web").Variable<string>;
        neutral10: import("@tamagui/web").Variable<string>;
        neutral11: import("@tamagui/web").Variable<string>;
        neutral12: import("@tamagui/web").Variable<string>;
    };
    font: {
        heading: import("@tamagui/web").Variable<string>;
        body: import("@tamagui/web").Variable<string>;
        mono: import("@tamagui/web").Variable<string>;
    };
    fontSize: {
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        11: import("@tamagui/web").Variable<number>;
        13: import("@tamagui/web").Variable<number>;
    };
    lineHeight: {
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        11: import("@tamagui/web").Variable<number>;
        13: import("@tamagui/web").Variable<number>;
    };
    fontWeight: {
        1: import("@tamagui/web").Variable<string>;
        2: import("@tamagui/web").Variable<string>;
        3: import("@tamagui/web").Variable<string>;
        4: import("@tamagui/web").Variable<string>;
        5: import("@tamagui/web").Variable<string>;
        6: import("@tamagui/web").Variable<string>;
        7: import("@tamagui/web").Variable<string>;
    };
    letterSpacing: {
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
    };
}, "color" | "space" | "size" | "radius" | "zIndex">, {
    light: {
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColor: string;
        borderColorHover: string;
        borderColorFocus: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
    dark: {
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColor: string;
        borderColorHover: string;
        borderColorFocus: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
    light_subtle: {
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColor: string;
        borderColorHover: string;
        borderColorFocus: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
    dark_subtle: {
        background: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColor: string;
        borderColorHover: string;
        borderColorFocus: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
    light_inverted: {
        background: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        borderColor: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColorHover: string;
        borderColorFocus: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
    dark_inverted: {
        background: string;
        color: string;
        colorHover: string;
        colorPress: string;
        colorMuted: string;
        borderColor: string;
        backgroundHover: string;
        backgroundPress: string;
        backgroundFocus: string;
        borderColorHover: string;
        borderColorFocus: string;
        colorInverse: string;
        placeholderColor: string;
        shadowColor: string;
        primary: string;
        primaryHover: string;
        primaryPress: string;
        primaryFocus: string;
        primaryBackground: string;
        primaryBackgroundHover: string;
        primaryBackgroundPress: string;
        primaryBorder: string;
        success: string;
        successHover: string;
        successPress: string;
        successBackground: string;
        successBackgroundHover: string;
        successBackgroundPress: string;
        successBorder: string;
        warning: string;
        warningHover: string;
        warningPress: string;
        warningBackground: string;
        warningBackgroundHover: string;
        warningBackgroundPress: string;
        warningBorder: string;
        error: string;
        errorHover: string;
        errorPress: string;
        errorBackground: string;
        errorBackgroundHover: string;
        errorBackgroundPress: string;
        errorBorder: string;
    };
}, {
    readonly ussel: "userSelect";
    readonly cur: "cursor";
    readonly pe: "pointerEvents";
    readonly col: "color";
    readonly ff: "fontFamily";
    readonly fos: "fontSize";
    readonly fost: "fontStyle";
    readonly fow: "fontWeight";
    readonly ls: "letterSpacing";
    readonly lh: "lineHeight";
    readonly ta: "textAlign";
    readonly tt: "textTransform";
    readonly ww: "wordWrap";
    readonly ac: "alignContent";
    readonly ai: "alignItems";
    readonly als: "alignSelf";
    readonly b: "bottom";
    readonly bc: "backgroundColor";
    readonly bg: "backgroundColor";
    readonly bbc: "borderBottomColor";
    readonly bblr: "borderBottomLeftRadius";
    readonly bbrr: "borderBottomRightRadius";
    readonly bbw: "borderBottomWidth";
    readonly blc: "borderLeftColor";
    readonly blw: "borderLeftWidth";
    readonly boc: "borderColor";
    readonly br: "borderRadius";
    readonly bs: "borderStyle";
    readonly brw: "borderRightWidth";
    readonly brc: "borderRightColor";
    readonly btc: "borderTopColor";
    readonly btlr: "borderTopLeftRadius";
    readonly btrr: "borderTopRightRadius";
    readonly btw: "borderTopWidth";
    readonly bw: "borderWidth";
    readonly dsp: "display";
    readonly f: "flex";
    readonly fb: "flexBasis";
    readonly fd: "flexDirection";
    readonly fg: "flexGrow";
    readonly fs: "flexShrink";
    readonly fw: "flexWrap";
    readonly h: "height";
    readonly jc: "justifyContent";
    readonly l: "left";
    readonly m: "margin";
    readonly mah: "maxHeight";
    readonly maw: "maxWidth";
    readonly mb: "marginBottom";
    readonly mih: "minHeight";
    readonly miw: "minWidth";
    readonly ml: "marginLeft";
    readonly mr: "marginRight";
    readonly mt: "marginTop";
    readonly mx: "marginHorizontal";
    readonly my: "marginVertical";
    readonly o: "opacity";
    readonly ov: "overflow";
    readonly p: "padding";
    readonly pb: "paddingBottom";
    readonly pl: "paddingLeft";
    readonly pos: "position";
    readonly pr: "paddingRight";
    readonly pt: "paddingTop";
    readonly px: "paddingHorizontal";
    readonly py: "paddingVertical";
    readonly r: "right";
    readonly shac: "shadowColor";
    readonly shar: "shadowRadius";
    readonly shof: "shadowOffset";
    readonly shop: "shadowOpacity";
    readonly t: "top";
    readonly w: "width";
    readonly zi: "zIndex";
}, {
    xs: {
        maxWidth: number;
    };
    sm: {
        maxWidth: number;
    };
    md: {
        maxWidth: number;
    };
    lg: {
        maxWidth: number;
    };
    xl: {
        maxWidth: number;
    };
    xxl: {
        maxWidth: number;
    };
    gtXs: {
        minWidth: number;
    };
    gtSm: {
        minWidth: number;
    };
    gtMd: {
        minWidth: number;
    };
    gtLg: {
        minWidth: number;
    };
    gtXl: {
        minWidth: number;
    };
    short: {
        maxHeight: number;
    };
    tall: {
        minHeight: number;
    };
    hoverNone: {
        hover: string;
    };
    hover: {
        hover: string;
    };
    pointerCoarse: {
        pointer: string;
    };
    pointerFine: {
        pointer: string;
    };
    reducedMotion: {
        prefersReducedMotion: string;
    };
}, {}, {}, {
    allowedStyleValues: "somewhat-strict-web";
    cssStyleSeparator: string;
    themeClassNameOnRoot: true;
    maxDarkLightNesting: number;
}>;
export type AppConfig = typeof config;
export type Conf = AppConfig;
export default config;
//# sourceMappingURL=tamagui.config.d.ts.map